In [25]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)
arr2= np.array([[1,2,3,4],
                [5,6,7,8]])
print(arr2)
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],
                  [[9,10,11,12],[1,2,3,4]]])
print(arr3)

print(arr1.size)
print(arr1.ndim)
print(arr3.shape)
print(arr1)

np.zeros((2,5))
np.ones((1,3))

np.random.seed(1)
arr1= np.random.randint(1,26,(2,3))
print(arr1)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 1  2  3  4]]]
4
1
(2, 2, 4)
[1 2 3 4]
[[ 6 12 13]
 [ 9 10 12]]


In [78]:
import numpy as np
# -10 ~10 사이의 정수로 (3,4) 모양의 배열을 만들고 arr1에 저장
np.random.seed(1)
arr1 = np.random.randint(-10,10,(3,4))
print(arr1)
# 아래와 같은 2차원 배열을 만들고 arr2에 저장
# 1,2,3,4
# 5,6,7,8
# 9,10,11,12
# 13,14,15,16
arr2 = np.array([[1,2,3,4],[5,6,7,8],
                 [9,10,11,12],[13,14,15,16]])

print(arr2)

# 1. 각 배열의 차원, 모양, 원소의 개수를 확인
print(arr2.ndim)
print(arr1.shape)
print(arr2.size)

# 2. arr1에서 행은 모두 출력하고 열은 첫번째, 세번째만 출력
print(arr1[::,:3:2])

# 3. arr2에서 아래처럼 나오게 인덱싱해주세요
# [5,7]
# [9,11]
print(arr2[1:3:,:3:2])

# 4. arr1에서 음수만 출력
print(arr1[arr1<0])

[[ -5   1   2  -2]
 [ -1   1  -5   5]
 [-10   6  -9   2]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
(3, 4)
16
[[ -5   2]
 [ -1  -5]
 [-10  -9]]
[[ 5  7]
 [ 9 11]]
[ -5  -2  -1  -5 -10  -9]


In [21]:
print("Hello")

Hello
